#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
 Simple keyboard shooter code in pygame
 
 Based on Sample Python/Pygame Programs
 Simpson College Computer Science
 http://programarcadegames.com/
 http://simpson.edu/computer-science/
 
"""

import pygame
import random
from random import randrange

# Define some colors

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
MAX_STARS = 30
STAR_SPEED = 3


# --- Classes

class Block(pygame.sprite.Sprite):

    """ This class represents the block. """

    def __init__(self):

        # Call the parent class (Sprite) constructor

        super().__init__()

        self.image = pygame.Surface([20, 15])
        self.image.fill(BLUE)

        self.rect = self.image.get_rect()

        # self.centre_x = 0
        # self.centre_y = 1

    def update(self):
        self.rect.x -= self.centre_y


class Player(pygame.sprite.Sprite):

    """ This class represents the Player. """

    def __init__(self, x, y):
        """ Set up the player on creation. """

        # Call the parent class (Sprite) constructor

        super().__init__()

        self.image = pygame.Surface([20, 20])
        self.image.fill(RED)

        self.rect = self.image.get_rect()
        self.rect.x = x
        self.rect.y = y

        # -- Attributes
        # Set speed vector

        self.change_x = 0
        self.change_y = 0

    def changespeed(self, x, y):
        """ Change the speed of the player"""

        self.change_x += x
        self.change_y += y

    def update(self):
        """ Find a new position for the player"""

        self.rect.x += self.change_x
        self.rect.y += self.change_y


class Bullet(pygame.sprite.Sprite):

    """ This class represents the bullet . """

    def __init__(self):

        # Call the parent class (Sprite) constructor

        super().__init__()

        self.image = pygame.Surface([10, 4])
        self.image.fill(WHITE)

        self.rect = self.image.get_rect()

    def update(self):
        """ Move the bullet. """

        self.rect.x += 6


# Players Health

def health_bar(player_health):
    if player_health > 75:
        player_health_color = GREEN
    elif player_health > 50:
        player_health_color = YELLOW
    else:
        player_health_color = RED
    pygame.draw.rect(screen, player_health_color, (130, 12,
                     player_health, 10))


# define and draw starfeild

def init_stars(screen):
    """ Create the starfield """

    global stars
    stars = []
    for i in range(MAX_STARS):

    # A star is represented as a list with this format: [X,Y]

        star = [randrange(0, screen.get_width() - 1), randrange(0,
                screen.get_height() - 1)]
        stars.append(star)


def move_and_draw_stars(screen):
    """ Move and draw the stars in the given screen """

    global stars
    for star in stars:
        star[0] -= STAR_SPEED

    # If the star hit the bottom border then we reposition
    # it in the top of the screen with a random X coordinate.

        if star[0] < 0:
            star[0] = screen.get_width()
            star[1] = randrange(0, 300)

        screen.set_at(star, (255, 255, 255))


# --- Create the window

# Initialize Pygame

pygame.init()

# Set the height and width of the screen

screen_width = 800
screen_height = 300
font = pygame.font.Font(None, 24)
screen = pygame.display.set_mode([screen_width, screen_height])

init_stars(screen)

# --- Sprite lists

# This is a list of every sprite. All blocks and the player block as well.

all_sprites_list = pygame.sprite.Group()

# List of each block in the game

block_list = pygame.sprite.Group()

# List of each bullet

bullet_list = pygame.sprite.Group()

# --- Create the sprites

# Create a red player block

player = Player(40, 100)
all_sprites_list.add(player)

# Loop until the user clicks the close button.

done = False

# Used to manage how fast the screen updates

clock = pygame.time.Clock()

score = 0
player.xspeed = 0
player.yspeed = 0
player_health = 100

# -------- Main Program Loop -----------

while not done:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True

        if event.type == pygame.KEYDOWN:

            # Fire a bullet if the user clicks the mouse button

            if event.key == pygame.K_z:
                bullet = Bullet()

            # Set the bullet so it is where the player is

                bullet.rect.x = player.rect.x + 20
                bullet.rect.y = player.rect.y + 5

            # Add the bullet to the lists

                all_sprites_list.add(bullet)
                bullet_list.add(bullet)

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_LEFT:
                player.changespeed(-3, 0)
            elif event.key == pygame.K_RIGHT:
                player.changespeed(3, 0)
            elif event.key == pygame.K_UP:
                player.changespeed(0, -3)
            elif event.key == pygame.K_DOWN:
                player.changespeed(0, 3)
        elif event.type == pygame.KEYUP:

        # Reset speed when key goes up

            if event.key == pygame.K_LEFT:
                player.changespeed(3, 0)
            elif event.key == pygame.K_RIGHT:
                player.changespeed(-3, 0)
            elif event.key == pygame.K_UP:
                player.changespeed(0, 3)
            elif event.key == pygame.K_DOWN:
                player.changespeed(0, -3)

    # --- Game logic

    # player.rect.x = player.rect.x + player.xspeed
    # player.rect.y = player.rect.y + player.yspeed

    if player.rect.x + 23 > 500:
        player.rect.x = 500 - 26
    elif player.rect.x + 3 < 40:
        player.rect.x = 40
    elif player.rect.y + 3 > 280:
        player.rect.y = 280
    elif player.rect.y < 3:
        player.rect.y = 0

    # Call the update() method on all the sprites

    # Calculate mechanics for each bullet

    for bullet in bullet_list:

        # See if it hit a block

        block_hit_list = pygame.sprite.spritecollide(bullet,
                block_list, True)

        # For each block hit, remove the bullet and add to the score

        for block in block_hit_list:
            bullet_list.remove(bullet)
            all_sprites_list.remove(bullet)
            block_list.remove(Block)
            all_sprites_list.remove(Block)
            score += 1

        # Remove the bullet if it flies up off the screen

        if bullet.rect.x > 810:
            bullet_list.remove(bullet)
            all_sprites_list.remove(bullet)

    for i in range(30):
        createblock = random.randrange(0, 8)
        if len(block_list) < 3 and createblock < 2:

            block = Block()
            block.rect.x = 800
            block.rect.y = random.randrange(10, screen_height - 20)
            block.centre_y = random.randrange(2, 5)

            block_list.add(block)
            all_sprites_list.add(block)

    for block in block_list:
        if block.rect.x < 0:
            block_list.remove(block)
            all_sprites_list.remove(block)
            score -= 1

    block_collided = pygame.sprite.spritecollide(player, block_list,
            True)

    if block_collided and player_health > 0:
        player_health = player_health - 5

    # --- Draw a frame

    all_sprites_list.update()

    # Clear the screen

    screen.fill(BLACK)
    health_bar(player_health)
    text = font.render('Score: ' + str(score), True, WHITE)
    screen.blit(text, [10, 10])

    # Draw all the spites

    all_sprites_list.draw(screen)

    # Go ahead and update the screen with what we've drawn.

    move_and_draw_stars(screen)
    pygame.display.flip()

    # --- Limit to 20 frames per second

    clock.tick(60)

pygame.quit()

			
